### ISSUE TITLE
Why does version LinqToTwitter v6.6.0 not work with .Net v4.8?

### ISSUE THREAD

**Issue by sqlcnet** [JoeMayo/LinqToTwitter#219]
My projects target .Net v4.8. When trying to install LinqToTwitter v6.6.0 it says your package cannot work with .Net v4.8. However, your latest v5 does work with .Net v4.8.

**Comment by JoeMayo** [comment]
LINQ to Twitter v6.x is a migration path to Twitter API v2 and only supports .NET 5+. I upgrade it every time the Twitter API v2 introduces/replaces another endpoint. LINQ to Twitter v5.x only supports Twitter API v1.1. During initial planning for Twitter API v2, I looked at the scenario where there were v2 APIs that replace v1.1 APIs. To support them both in the same library would have either introduced breaking changes or complicated naming. Additionally, Twitter API v2 is not a clean 1-to-1 endpoint mapping. At the time I had to make the decision, the easiest way was to go with the clean break.

Nearly a year ago, I published [LINQ to Twitter v6.0 Themes](https://medium.com/general-thoughts/linq-to-twitter-v6-0-themes-fdcb8b9c53d5), hoping to get some feedback on my approach. So far, the feedback on my choices has been positive. As always, I'm open to new ideas.

In LINQ to Twitter v5.x, you still have the ability to access Twitter API v2, through [Raw Command and Queries](https://www.linqtotwitter.com/LINQ-to-Twitter-5/Safety-Hatch.html).

**Comment by sqlcnet** [comment]
I have no problem with the migration path split. That was an excellent plan. But I still don't understand why when I try to update my solution to v6.6.0 via Nuget Package, I get the following error:

Could not install package 'linqtotwitter 6.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

It seems the Nuget Package update for v6.6.0 has depency check settings that do not allow it to work with solutions targeting .Net v.4.8. What is it about v6.6.0 that made you to say that it can only supports .NET 5+? My understanding is all new .NET versions should be backward compatible.

I am updated to .NET 5.0.202 per updates from 16.9.4 of visual studio installer. But, under Project Properties / Application, there is no option to set .Net 5.0. The max is v4.8.

My project has run with v4.8 target framework and LinqToTwitter v5.1.3 for years. What coding changes did you make in v6.6.0 that requires it to run only with .NET 5+? My guess is it will still be good with earlier .Net versions but you just decided to make dependency settings using the latest available at the time. Perhaps you only need to make a minor change to the Nuget package settings.

**Comment by JoeMayo** [comment]
I'll have to learn more about the framework compatibility story to get a full understanding. Here's my `LinqToTwitter.nuspec` in case you see something:

	<?xml version="1.0" encoding="utf-8"?>
	<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
	  <metadata>
		<id>linqtotwitter</id>
		<version>6.6.0</version>
		<authors>Joe Mayo</authors>
		<requireLicenseAcceptance>false</requireLicenseAcceptance>
		<license type="expression">Apache-2.0</license>
		<licenseUrl>https://licenses.nuget.org/Apache-2.0</licenseUrl>
		<icon>200xColor_2.png</icon>
		<projectUrl>https://github.com/JoeMayo/LinqToTwitter</projectUrl>
		<description>LINQ to Twitter is a 3rd party LINQ Provider that lets you tweet and query with the Twitter API.</description>
		<releaseNotes>- Added the BlockUserAsync and UnblockUserAsync to support the new Twitter API v2 endpoints.
	- Removed CreateBlockAsync and DestroyBlockAsync from the deprecated Twitter API v1.1 endpoints.</releaseNotes>
		<tags>twitter twitterapi twitterdev tweet linq social linqtotwitter linq2twitter</tags>
		<repository url="https://github.com/JoeMayo/LinqToTwitter" />
		<dependencies>
		  <group targetFramework="net5.0">
			<dependency id="System.Text.Json" version="5.0.1" exclude="Build,Analyzers" />
		  </group>
		</dependencies>
	  </metadata>
	</package>

**Comment by sqlcnet** [comment]
I too need to learn more. But my understanding is a library can target multiple frameworks at the same time. My guess is when you created LinqToTwitter v6+ you created a new project in Visual Studio using a .Net Core template, which defaulted all to target framework net5.0, and nothing but net5.0. But nothing in the LinqToTwitter code changes used API’s only found in net5.0+. The code probably is still fully compatible with net48 and earlier.

I found this article where your LinqToTwitter .csproj file can target multiple frameworks:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file

Note: You have to change the `<TargetFramework>` element to plural (with s) `<TargetFrameworks>` such as `<TargetFrameworks>net5.0;net48</TargetFrameworks>`.

And then for the .nuspec file I found this article:
https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#declaring-dependencies-advanced

For example,

```
<dependencies>
    <group targetFramework="net5.0">
	<dependency id="System.Text.Json" version="5.0.1" exclude="Build,Analyzers" />
    </group>
    <group targetFramework="net48">
    </group>
</dependencies>
```


Perhaps this can help.

**Comment by JoeMayo** [comment]
Thanks for the feedback. The problem is that I'm using newer language and .NET features that aren't compatible.  I can get a .NET Standard 2.1 build, but .NET Standard 2.0 doesn't build. Although that doesn't provide the answer  some folks would like, and I'm sorry about that, it feels like I'm making the right decision where the momentum is moving forward.

The good news is that there's still time before Twitter deprecates v1.1 (check with their developer site for timing). In the meantime, you can still use LINQ to Twitter 5.x [Raw Queries and Commands](https://www.linqtotwitter.com/LINQ-to-Twitter-5/Safety-Hatch.html) to access Twitter API v2 endpoints.
